version: "3.2"

services:
  web-front:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    expose:
      - "80"
    networks:
      - elk

networks:
  elk:
    driver: bridge
