const DUMMY = [
  {
    id: 1,
    title: `제목1`,
    price: 1000,
    content: `내용1`,
    createDate: `2023-08-09`,
    category: `가전제품`,
    thumb: "https://cdn.vuetifyjs.com/images/john.jpg",
    like: true,
  },
  {
    id: 2,
    title: `제목2`,
    price: 2000,
    content: `내용2`,
    createDate: `2023-08-10`,
    category: `가전제품`,
    thumb: "https://cdn.vuetifyjs.com/images/john.jpg",
    like: true,
  },
  {
    id: 3,
    title: `제목3`,
    price: 3000,
    content: `내용3`,
    createDate: `2023-08-11`,
    category: `가전제품`,
    thumb: "https://cdn.vuetifyjs.com/images/john.jpg",
    like: true,
  },
  {
    id: 4,
    title: `제목4`,
    price: 4000,
    content: `내용4`,
    createDate: `2023-08-12`,
    category: `가구`,
    thumb: "https://cdn.vuetifyjs.com/images/john.jpg",
    like: true,
  },
  {
    id: 5,
    title: `제목4`,
    price: 4000,
    content: `내용4`,
    createDate: `2023-08-12`,
    category: `가구`,
    thumb: "https://cdn.vuetifyjs.com/images/john.jpg",
    like: true,
  },
  {
    id: 6,
    title: `제목4`,
    price: 4000,
    content: `내용4`,
    createDate: `2023-08-12`,
    category: `가전제품`,
    thumb: "https://cdn.vuetifyjs.com/images/john.jpg",
    like: true,
  },
];

export default DUMMY;
